app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: password
    pool-size: 30

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true